### ISSUE TITLE
layout : steps shouldn't be in line with workflow outputs

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#104]
see https://view.commonwl.org/workflows/github.com/ProteinsWebTeam/ebi-metagenomics-cwl/tree/823cdf7a6601a3799f6167f3566ae02590748f6b/workflows/emg-pipeline-v3.cwl

**Comment by MarkRobbo** [comment]
I'm not sure if I can do anything about this one due to the way DOT ranking works (though I am not very familiar, it might well be possible). I will have to research it.

**Comment by MarkRobbo** [comment]
One way I have found to solve this is to use an invisible constraint

```
lowStepNode -> outputNode [style=invis];
```

But due to not actually knowing whether this is necessary at the time of generation, this must be added from every single step to an output node which messes up the DOT source.

**Comment by mr-c** [comment]
Sounds like a reasonable workaround for now. You could add a comment to that section of the  DOT source to explain what is going on
