### ISSUE TITLE
Color legend

### ISSUE THREAD

**Issue by buchanae** [common-workflow-language/cwlviewer#110]
The boxes in have various colors, but I have no idea what the colors mean. Could you add a simple legend? (Or does it exist and I'm blind?)

**Comment by MarkRobbo** [comment]
It doesn't exist actually, I did overlook that. Blue is just to differentiate inputs and outputs, purple is for default values coming into inputs for a step, and the regular steps are yellow.

I'll try to fit that in somewhere
