### ISSUE TITLE
Internal server error on github CWL repo

### ISSUE THREAD

**Issue by jasonwalker80** [common-workflow-language/cwlviewer#118]
Many of the workflows in this repo are parsed and viewed correctly when provided a sub-directory, ex. unaligned_bam_to_bqsr:
https://github.com/genome/cancer-genomics-workflow/tree/toil_compatibility

Here is a link to one that works:
https://view.commonwl.org/workflows/github.com/genome/cancer-genomics-workflow/tree/toil_compatibility/unaligned_bam_to_bqsr/workflow.cwl

However, this one specifically causes an error:
https://view.commonwl.org/workflows/github.com/genome/cancer-genomics-workflow/tree/toil_compatibility/detect_variants/detect_variants.cwl

**Comment by MarkRobbo** [comment]
Change is live and fixed the mentioned workflow. Thanks for the issue
