### ISSUE TITLE
No need for JSESSION cookie

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwlviewer#122]
When trying to embed the SVG as an `<img>` in a different web page, for instance in http://bioexcel.eu/software/workflows/#workflow-blocks - then it seems to set a `JSESSION` cookie.

This can trigger [Privacy Badger](https://www.eff.org/privacybadger) and block the resource.

We should not need a cookie as all our resources are RESTful - so I think we can disable cookies from the Spring Web framework for all resources.

**Comment by MarkRobbo** [comment]
Set by [Spring Security](https://projects.spring.io/spring-security/) but looks like this can be disabled with configuration, as we do not use the authentication or session features

**Comment by obasekiosa** [comment]
> When trying to embed the SVG as an `<img>` in a different web page, for instance in http://bioexcel.eu/software/workflows/#workflow-blocks - then it seems to set a `JSESSION` cookie.
> 
> 
> 
> This can trigger [Privacy Badger](https://www.eff.org/privacybadger) and block the resource.
> 
> 
> 
> We should not need a cookie as all our resources are RESTful - so I think we can disable cookies from the Spring Web framework for all resources.


I can't seem to reproduce this issue.  
How were you able to reproduce it?

I tried embedding the svg link referenced in the bioexcel website into an img locally to see if the cookies would be generated but non were generated.

I also tried tried some other svg links from the main website and then my local setup.

Then I checked bioexcel site for cookies and I found no JSESSION cookie.
 I also checked the pages I created locally, the same result.

**Comment by tetron** [comment]
Did you check the actual HTTP response from cwlviewer, to see if it returned a cookie in the header?  Web browsers have more strict about cross-site cookies, and so it may have been blocked.  So it would not show up as being set, but it might still have been sent incorrectly.

**Comment by obasekiosa** [comment]
> Did you check the actual HTTP response from cwlviewer, to see if it returned a cookie in the header?  Web browsers have more strict about cross-site cookies, and so it may have been blocked.  So it would not show up as being set, but it might still have been sent incorrectly.

Yes I did, no cookies where returned.

**Comment by mr-c** [comment]
Okay, closing this issue as it seems to be fixed. Thanks!
