### ISSUE TITLE
Provide preferred citation for the CWL viewer

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#132]
Embed in the generated RO as well?

I've found the following DOIs -- which is preferred?

https://doi.org/10.5281/zenodo.823535

https://doi.org/10.7490/f1000research.1114375.1

**Comment by MarkRobbo** [comment]
For now we would prefer that the poster is cited - https://doi.org/10.7490/f1000research.1114375.1

This is clarified by the about page which is ready to be merged
