### ISSUE TITLE
DOT graph generation

### ISSUE THREAD

**Issue by MarkRobbo** [common-workflow-language/cwlviewer#14]
The first task related to visualisation will be to get the server generating simple [DOT graphs](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) for the steps in the workflow and including these in the page

**Comment by stain** [comment]
Do we want to expose this also as a downloadable resource, e.g. `/dot` or `.dot`?   

SVG could then later be done as `.svg` (that would have to call `dot` installed on the server, which we can add to the `Dockerfile` with an `apt-get install graphviz`)
