### ISSUE TITLE
Main workflow discovery

### ISSUE THREAD

**Issue by MarkRobbo** [common-workflow-language/cwlviewer#16]
Currently the main workflow if there are multiple in the same group of files is chosen in the 'dumb' way of the first one we come across.

Ideally we would look at the relationships between the workflows and choose the largest to display (or perhaps even add an additional step to ask the user if it is not clear (though this brings up additional issues with caching if future users wanted a different workflow - would the ID change somehow?)

**Comment by mr-c** [comment]
Yeah, it would be really nice to be able to override this.

**Comment by mr-c** [comment]
For example, by providing the full URL to the workflow:https://github.com/NCI-GDC/gdc-dnaseq-cwl/blob/master/workflows/dnaseq/transform.cwl
