### ISSUE TITLE
unicode locale missing from view.commonwl.org service

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#174]
```
The error was: 'ascii' codec can't encode character u'\u2019' in position 9238: ordinal not in range(128)
```

From https://view.commonwl.org/workflows/github.com/MG-RAST/amplicon/blob/wilke/cwl/CWL/Workflows/tap.prok.workflow.cwl

**Comment by alexbarrera** [comment]
@mr-c I assume the error you were having is gone since the link to the workflow view works well. I'm having an equivalent issue, any hint on what was causing this for you? 
From https://view.commonwl.org/workflows/github.com/alexbarrera/GGR-cwl/blob/master/v1.0/ATAC-seq_pipeline/pipeline-pe.cwl#

**Comment by mr-c** [comment]
@alexbarrera It may not have been fixed properly. Here's an updated URL: https://view.commonwl.org/workflows/github.com/MG-RAST/amplicon/blob/master/CWL/Workflows/tap.prok.1.0.cwl# The workaround is to remove non-ASCII characters from your CWL descriptions :-(
