### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#186]
https://github.com/ga4gh/dockstore/issues/1058#issuecomment-355166878

Will allow embedding of the visualizations in other websites without server side coordination.

Seems like adding the HTTP header `Access-Control-Allow-Origin: *` would be sufficient

**Comment by coverbeck** [comment]
@stain Do you know when this and #189 will be deployed to your production instance?

Thanks,

Charles
