### ISSUE TITLE
Viewer Does Not Work Against Git Tags

### ISSUE THREAD

**Issue by coverbeck** [common-workflow-language/cwlviewer#191]
## Description
If you specify a CWL URL with a Git Tag, the Common Workflow Language Viewer displays the error `The workflow could not be retrieved from the Git repository using the details given`.

## Expected Behavior
Viewer should be able to visualize a CWL off of a tag, just as it does for branches.

## Actual Behavior
It displays an error message.

## Possible Fix
In GitService.java there is 
```
branchOrCommitId = "refs/remotes/origin/" + branchOrCommitId;
```
According to https://stackoverflow.com/questions/33762575/load-content-from-tag-with-jgit, you need to set it to "refs/tags/my-tag" ) if it's a tag.

## Steps to Reproduce

1. Go to https://view.commonwl.org/workflows
2. Input this value for the Url to workflow: `https://github.com/briandoconnor/dockstore-workflow-md5sum/blob/1.3.0/md5sum.cwl` 
3. You get the error `The workflow could not be retrieved from the Git repository using the details given`

## Context

I'm working on using images generated by the viewer and displaying them in dockstore.org; in trying different workflows, I stumbled across this one.

**Comment by mr-c** [comment]
Thanks @coverbeck for your report! Can you make a quick PR to add the tag version as a fallback? I don't think any fancy (is this a tag or commit) logic is needed 🙂

**Comment by coverbeck** [comment]
@mr-c : https://github.com/common-workflow-language/cwlviewer/pull/192

**Comment by mr-c** [comment]
Thanks @coverbeck , I don't have the expertise nor the permissions to review your PR

**Comment by coverbeck** [comment]
Added some tests to the PR.
