### ISSUE TITLE
Workflow visualization not working on online version

### ISSUE THREAD

**Issue by r78v10a07** [common-workflow-language/cwlviewer#220]
I'm trying to visualize my workflows on Gitlab using the public cwlviewer https://view.commonwl.org/workflows but it is not working. I installed a local version with Docker as described in the README and the visualization works fine.

The workflow:

https://gitlab.com/r78v10a07/cwl-workflow/blob/master/workflows/ChIP-exo/peak_caller-SE.cwl

## Expected Behavior
![ChIP-Seq-workflow](https://user-images.githubusercontent.com/8643256/55026190-e3822c00-4fd8-11e9-811e-e5c9d013b7f3.png)

## Actual Behavior
![Screen Shot 2019-03-26 at 3 06 09 PM](https://user-images.githubusercontent.com/8643256/55026228-f72d9280-4fd8-11e9-8925-eae9dd99856b.png)

Thanks,
Roberto

**Comment by pvanheus** [comment]
I get the same error with: https://github.com/pvanheus/protein_evidence_mapping/blob/master/protein_evidence_mapping.cwl - this also works with the local Docker version but neither on the online view.commonwl.org nor on view.commonwl.org:8082

**Comment by mr-c** [comment]
Looks like this was fixed
