### ISSUE TITLE
error in visualizing the workflow

### ISSUE THREAD

**Issue by matmanc** [common-workflow-language/cwlviewer#226]
Hi we tried to visualize the workflow in the repository 
https://git.astron.nl/eosc/prefactor3-cwl/prefactor_calibrator.cwl
with this permalink:
https://w3id.org/cwl/view/git/c2a0646544695a8ba53ffb33375115bbf802b2dd/prefactor_calibrator.cwl
It seems to generate part of the figure until it finishes displaying nothing.

**Comment by stain** [comment]
I wonder if this  is related to `id` field https://git.astron.nl/eosc/prefactor3-cwl/blob/master/prefactor_calibrator.cwl#L3

**Comment by mr-c** [comment]
Looks like this was fixed
