### ISSUE TITLE
issue with optional secondaryFiles from v1.1?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#227]
cwltool --validate https://raw.githubusercontent.com/icgc-argo/dna-seq-processing-wfs/master/workflows/dna-seq-alignment/cwl/dna-seq-alignment.cwl
has warnings, but passes

https://view.commonwl.org/workflows/github.com/icgc-argo/dna-seq-processing-wfs/blob/master/workflows/dna-seq-alignment/cwl/dna-seq-alignment.cwl# fails

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Java 1.8):

**Comment by stain** [comment]
From server:

```
bash-4.4#  cwltool --validate https://raw.githubusercontent.com/icgc-argo/dna-seq-processing-wfs/master/workflows/dna-seq-alignment/cwl/dna-seq-alignment.cwl

INFO /usr/bin/cwltool 1.0.20190915164430
ERROR Tool definition failed initialization:
Tool definition https://raw.githubusercontent.com/icgc-argo/data-processing-utility-tools/payload-generation.0.1.5/tools/payload-generation/payload-generation.cwl failed validation:
  Syntax error while parsing a flow sequence
    in "https://raw.githubusercontent.com/icgc-argo/data-processing-utility-tools/payload-generation.0.1.5/tools/payload-generation/payload-generation.cwl", line 32, column 21
  expected ',' or ']', but got '?'
    in "https://raw.githubusercontent.com/icgc-argo/data-processing-utility-tools/payload-generation.0.1.5/tools/payload-generation/payload-generation.cwl", line 32, column 26
```

btw, not sure why `cwltool` is logging in ANSI colours when it's not a terminal, it happens even if I do `2>err  `

Using `pip install --upgrade` I've updated to:

* schema-salad-4.5.20191023134839
* cwltool-1.0.20191022103248
* ruamel.yaml-0.16.0-py2.py3-none-any.whl

which thereafter works, but gives plenty of warnings.

BTW, why is still ruamel.yaml later than 0.16.0 impossible? It means it's hard to update it, I had to uninstall `ruamel.yaml` then reinstall `cwltool` to get the latest compatible version of ruamel..

**Comment by stain** [comment]
Of course https://view.commonwl.org/workflows/github.com/icgc-argo/dna-seq-processing-wfs/blob/master/workflows/dna-seq-alignment/cwl/dna-seq-alignment.cwl# is now broken in display, probably #228 

why is everyone using `id` ? :)

**Comment by mr-c** [comment]
@stain 
> why is everyone using `id` ? :)

Because the Rabix Composer adds an `id` by default :-(
