### ISSUE TITLE
Clicking "Last" on the Explore page gives ISE

### ISSUE THREAD

**Issue by tfmorris** [common-workflow-language/cwlviewer#270]
The URL that it goes to is https://view.commonwl.org/workflows?page=1982&size=10
changing this to https://view.commonwl.org/workflows?page=1982&size=1 correctly renders a page with a single entry.

p.s. it's cute how `Error: An internal server error occurred` is followed by "If this error was unexpected...". I'd suggest that logging Internal Server Errors might be useful. They rarely are expected or anything good.

**Comment by stain** [comment]
It is caused by error:

```
spring_1  | 2020-10-22 13:20:08.142 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 96 and error message 'Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.' on server mongo:27017; nested exception is com.mongodb.MongoQueryException: Query failed with error code 96 and error message 'Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.' on server mongo:27017] with root cause
```

Happening from this controller:

https://github.com/common-workflow-language/cwlviewer/blob/main/src/main/java/org/commonwl/view/workflow/WorkflowController.java#L94

calling

https://github.com/common-workflow-language/cwlviewer/blob/main/src/main/java/org/commonwl/view/workflow/WorkflowService.java#L97


Workaround added to production instance:

```
mongo --eval 'db.workflow.createIndex({ retrievedOn: 1})'
```

**Comment by stain** [comment]
Tried to fix in https://github.com/common-workflow-language/cwlviewer/blob/main/src/main/java/org/commonwl/view/workflow/Workflow.java but it needs to be tested!

**Comment by stain** [comment]
To test this would need to import all the old content:

https://github.com/common-workflow-language/cwlviewer/blob/main/dump.sh can dump a JSON file of all workflows from the production instance https://view.commonwl.org/

https://github.com/common-workflow-language/cwlviewer/blob/main/load.py can process your JSON file to refresh a new instance - you can use that as starting point for picking up fields

**Comment by mr-c** [comment]
Seems to be fixed!
