### ISSUE TITLE
Internationalize shown date format

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwlviewer#28]
> Fetched Dec 5 2016 at 02:22 GMT

.. seems a bit localized (US?) and also seems to say "02" instead of "14".

Should probably better be in international [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format, something like:

> Fetched 2016-12-05 14:22:00Z

**Comment by MarkRobbo** [comment]
`yyyy-MM-dd HH:mm:ss z` is now the format ie `2016-12-05 13:35:55 GMT`

I messed up on the 12 vs 24 hour time in the pattern previously
