### ISSUE TITLE
Permalinks / URI format

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwlviewer#29]
Now the POST of the github URL redirects to a mongodb-generated ID like http://view.commonwl.org:8080/workflows/58457819857aba0001b0077e -- but `58457819857aba0001b0077e` is based on an internal mongodb id, and would be a different if the mongodb was flushed.

Better would be an identifier hashed from the git commit and subpath, rendered with `[a-zA-Z0-9]` instead of hexadecimal, e.g. `https://view.commonwl.org/workflows/aPs812/`

Determining the git commit of a folder can be tricky (one has to check latest commit of every file in the subtree) -- it could be based on the last commit pointed to instead (which could change more rapidly, but hey..)

This means a fresh install populated with the same github URLs would give the same identifier.

Convenience linkable URLs based on GitHub URL (e.g. `https://view.commonwl.org/workflows/github.com/common-workflow-language/workflows/blob/920c6be45f08e979e715a0018f22c532b024074f/workflows/lobSTR`) would also be nice (it could redirect to the short one)  - but that's a separate issue.

**Comment by MarkRobbo** [comment]
This is a tough one - it's very difficult to get a reliable hash without collisions which is also that short.

One approach would be to use an indexed secondary ID in MongoDB but this does not fix the odd collision if we are simplifying such a large hash like commit ID and path down to a very simple one. It is preferable not to have to query the database even on an indexed field just to make sure it is unique, so a counter would probably have to be used as part of the hash (similar to URL shorteners) which then breaks the requirement of "fresh install populated with the same Github URLs would give the same identifier"

I think a better approach might be the URL based on Github URL and I have experimented with a controller method for this in addb177

This means you would be redirected to, for example, `https://view.commonwl.org/workflows/github.com/common-workflow-language/workflows/tree/master/workflows/lobSTR` and act as a consistent permalink.

@stain Do you think this is a sensible approach or do you have any ideas on hashing if you would prefer an approach with shortened IDs

What is the preferable approach for the user manually changing the URL to something not in the database yet through the main page, attempting to generate a new workflow so it is hackable, or just returning a 404 as it hasn't been retrieved yet?

**Comment by MarkRobbo** [comment]
Closed by #33

**Comment by stain** [comment]
Documented in https://github.com/common-workflow-language/cwlviewer/wiki/Permalinks
