### ISSUE TITLE
adding cwlviewer installation steps in ReadMe.md

### ISSUE THREAD

**Issue by Anushka-shukla** [common-workflow-language/cwlviewer#307]
Adding  installation steps in ReadMe to get the application running in local system

## Description
In the ReadMe.MD it's nowhere mentioned that first, you have to clone, and then inside the project directory we have to run: "docker-compose up". This can be a little confusing for the first-timers.

## Context
I was trying to get the application running on my system. I downloaded docker and docker-compose as it was upfront mentioned, then it was mentioned to run : docker-compose up. This started giving me below error:

Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?
    Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml"

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwlviewer/pull/308 ; thanks!
