### ISSUE TITLE
Not showing all the outputs of a workflow?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#31]
https://view.commonwl.org/workflows/5857df62857aba000107db47

From https://github.com/mr-c/hive-cwl-examples

**Comment by mr-c** [comment]
Ah, this is just picking a random `.cwl` file, which happens to be a `CommandLineTool` instead of the `Workflow` in the directory. Probably related to #16

**Comment by MarkRobbo** [comment]
That is correct, picking up one of the tools due to a mistake. Fixed when 8801806 is merged, after I have fully implemented step parsing
