### ISSUE TITLE
URL for port 8080 in README.md should be fixed

### ISSUE THREAD

**Issue by yichiehc** [common-workflow-language/cwlviewer#310]
URL for port 8080 in line 52 in README.md should be `http://localhost:8080/` instead of `https://localhost:8080/`.

Would be happy to make a pull request for this if needed.

**Comment by tetron** [comment]
Please do make a pull request.

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwlviewer/commit/224cbe32225e06d5454dede92bc971fd16def0d1
