### ISSUE TITLE
Migrate from TravisCI to GitHub Actions

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#318]
This is needed to be able to merge any pull requests, as the tests are not being run currently.

**Comment by Anushka-shukla** [comment]
Hey, @mr-c I can do this! Can you please assign this one to me?

**Comment by mr-c** [comment]
@Anushka-shukla Done!

**Comment by Anushka-shukla** [comment]
Hey, @mr-c I've opened this draft PR can you please provide feedback on this?
