### ISSUE TITLE
Adding Changelog with version release and release notes

### ISSUE THREAD

**Issue by Anushka-shukla** [common-workflow-language/cwlviewer#328]
We do not have the changelogs for this project yet.

## Description
It would help developers to precisely see what notable changes have been made between each release of the project.

**Comment by Anushka-shukla** [comment]
From where I can get the information that is required to be put in changelogs.

**Comment by obasekiosa** [comment]
> From where I can get the information that is required to be put in changelogs.


You can generate a change log using information from the git history of the project.

Simple change logs can be generated with the "git log [- options]" command .
More sophisticated logs can be generated using some external packages.

**Comment by Anushka-shukla** [comment]
yes I was thinking to automate this process somehow. GitHub provides such facility now.

**Comment by obasekiosa** [comment]
> yes I was thinking to automate this process somehow. GitHub provides such a facility now. Thanks for sharing it.

Oh alright.
Setting up a workflow to do this or if you prefer adapting an adequate one from GitHub market place should work.

**Comment by mr-c** [comment]
> You can generate a change log using information from the git history of the project.

This requires everyone to write the best possible git commit message and have very clean git histories. While people are capable of this, it is more work for contributors, so I would prefer hand written changelogs.

**Comment by Anushka-shukla** [comment]
Hey @mr-c, I have created a draft PR for this. Can you please provide feedback?

**Comment by mr-c** [comment]
This was done; thanks all!
