### ISSUE TITLE
Upgrade jgit from 5.x to 6.x

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwlviewer#367]
Upgrade jgit to 6.x or greater.

## Description

During the SpringBoot upgrade #284 , I tried upgrading jgit but it failed with one of those messages about the compiled bytecode version not matching... that code 52 and 54 I think? Unfortunately I didn't copy the message to check the minimum requirements, and the source code is hidden somewhere in the Eclipse code repositories (couldn't locate the sources in the jgit page :disappointed: ).

I reverted the change since that issue/PR was about SpringBoot and didn't want to spend much longer on that. So for later, we can try to upgrade it again, take care to record any issues/errors, and investigate what went wrong, why, and how to fix.

## Context

https://github.com/common-workflow-language/cwlviewer/pull/284#discussion_r771797284

**Comment by mr-c** [comment]
Fixed in #413
