### ISSUE TITLE
Update Changelog for v1.4.1 and release

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#371]
https://github.com/common-workflow-language/cwlviewer/compare/v1.4...main

**Comment by kinow** [comment]
I will leave this one for next week. Will describe what I did in that PR, and also try to include the other commits :+1: 

Thanks @mr-c

**Comment by kinow** [comment]
Created a page to help future release-managers https://github.com/common-workflow-language/cwlviewer/wiki/Release-checklist

**Comment by kinow** [comment]
Closing as I believe this is done @mr-c :+1: 

https://github.com/common-workflow-language/cwlviewer/releases
