### ISSUE TITLE
Need better error message when a CommandLineTool is submitted

### ISSUE THREAD

**Issue by mexanick** [common-workflow-language/cwlviewer#582]
## Description

CWL Viewer cannot find a workflow in gitlab (self-hosted) repository. 
## Expected Behavior

CWL Viewer shall find and parse the workflow correctly
## Actual Behavior

Error: The workflow could not be found within the repository
## Possible Fix

Must be related to #424
## Steps to Reproduce

1. Go to the https://view.commonwl.org/ and paste the address of the repository https://gitlab.cta-observatory.org/cta-computing/dpps/dpps-workflows.git as URL to workflow. 
2. Paste this commit hash: 76f7c25c0472da23b7e0bfe9f2c18ab6bc369c9d to the "Branch Name/Commit ID" field 
3. Now, the workflow that has been previously registered (long time ago) works: /workflows/calibpipe/uc-cp-001.cwl
4. However, the other workflow (that has not been registered before) doesn't: /workflows/datapipe/uc-dp-XXX.cwl

## Context

I can't render my workflows
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Java 17):

**Comment by mexanick** [comment]
Ah, I see! This explains things! Right, can you please improve the error message? :)

**Comment by kinow** [comment]
> We should have given a better error message in this instance.

+1
