### ISSUE TITLE
Update copyright text

### ISSUE THREAD

**Issue by stain** [common-workflow-language/cwlviewer#8]
The footer says

> Copyright here or links to ...

It should probably also link to this repository.

**Comment by MarkRobbo** [comment]
Do you have anything in mind for what exactly this should be updated to? 

I originally added the current text as a placeholder because I did not know what should be included

**Comment by stain** [comment]
Something like

[CWL Viewer] (c) 2016 [Common Workflow Project] and [contributors],
distributed under [Apache license, version 2.0]. [Shown workflow] has
separate copyright and license.

Links to: Cwlviewer GitHub repo. Commonwl.org, GitHub organization team
(which include you? Check your profile membership is public),
apache.org/licenses/LICENSE-2.0 (or so), GitHub URL of shown workflow.

(You may want to drop the last link if it's difficult to add to the header
dynamically)

**Comment by MarkRobbo** [comment]
#10 includes the addition to the footer dynamically as you mentioned
