### ISSUE TITLE
correctly draw graph when a workflow level input & output share the same name

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwlviewer#99]
https://view.commonwl.org/workflows/github.com/roryk/salmon-cwl/tree/master///salmon-workflow.cwl

See `index` in the linked workflow

**Comment by MarkRobbo** [comment]
@mr-c Is this valid as a workflow under the rules of salad-schema?

I had a similar issue #56 earlier and closed it due to [a discussion that this is technically possible in cwltool but is actually considered not valid](https://github.com/common-workflow-language/schema_salad/issues/56).

**Comment by mr-c** [comment]
Yes, this is valid and reasonable (a benefit of the scoping rules)

Pe 3 apr. 2017 18:17, "Mark Robinson" <notifications@github.com> a scris:

@mr-c <https://github.com/mr-c> Is this valid as a workflow under the rules
of salad-schema?

I had a similar issue #56
<https://github.com/common-workflow-language/cwlviewer/issues/56> earlier
and closed it due to a discussion that this is technically possible in
cwltool but is actually considered not valid
<https://github.com/common-workflow-language/schema_salad/issues/56>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/common-workflow-language/cwlviewer/issues/99#issuecomment-291175151>,
or mute the thread

**Comment by MarkRobbo** [comment]
@mr-c I would like some clarification on this issue. In the current version of `schema salad`/`cwltool` the following error is thrown due to the "index" ID being reused

"object id `https://cdn.rawgit.com/roryk/salmon-cwl/9772782d041c4d0a180fc89d55c83c31b24bb6af/salmon-workflow.cwl#index` previously defined"

Is this a bug in `cwltool` or is this no longer considered valid?

**Comment by mr-c** [comment]
Looks like the spec says "unique over the entire document", so an `input` and an `output` cannot share the same ID -- so I'll close this issue.
